apiVersion: v1
kind: Template
labels:
  template: tjx-dealservice-jenkinsfile
metadata:
  name: tjx-dealservice-jenkinsfile
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "dealservice-jenkinsfile", "namespace": "", "kind": "DeploymentConfig"}]'
    labels:
      application: ${APPLICATION_NAME}-jenkinsfile
    name: ${APPLICATION_NAME}-jenkinsfile
  spec:
    source:
      git:
        ref: ${SOURCE_REF}
        uri: ${SOURCE_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
      type: Generic
    triggers:
    - github:
        secret: kJZLvfQr3hZg
      type: GitHub
    - generic:
        secret: kJZLvfQr3hZg
      type: Generic
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: jkf-tasks
- description: The name of Dev project
  name: DEV_PROJECT
  required: true
  value: ocp-tasks
- description: Git source URI for application
  name: SOURCE_URL
  required: true
  value: https://github.com/way2arun/nodeJSDocker
- description: Git branch/tag reference
  name: SOURCE_REF
  value: master
